name: flutter_intent_test
description: Flutter intent test

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:

  sdk: ">=2.16.1 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  android_intent_plus: ^3.1.1
  url_launcher: ^6.0.18

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
